### ISSUE TITLE
CurSearch is ignored only when using tint.nvim

### ISSUE THREAD

**Issue by andrewferrier** [levouh/tint.nvim#11] opened 2022-09-04 18:44 UTC
I use https://github.com/ellisonleao/gruvbox.nvim as my colorscheme. Using this with tint, most stuff seems to work well. However, `CurSearch` - the highlight group used to highlight the search item the cursor is currently on (as opposed to the other matches in the buffer) - does not seem to work, although only when using tint.nvim. For me, the match the cursor is on is shown in the standard Normal color it would be in if not highlighted. If I remove `tint.nvim`, it starts working again.

The strange thing is that in both cases if I looked at highlight groups using `:highlight`, `CurSearch` is shown as `cleared`.

I'm not sure if this is a bug in NeoVim or tint. 

Please let me know if there's other information I can provide to help with recreation. Thanks for your hard work on this plugin.

**Comment by levouh** [comment] 2022-09-04 18:52
I've seen this as well actually, and it appears to be an issue with colors that are linked to other groups.

The issue I've seen is that `tint` copies from the highlights returned by `nvim__get_hl_defs` (granted, a non-stable API function). Some of the `TS*` groups, for instance, are linked to `Error` by default. After `tint` runs its setup, the namespaces it uses to highlight are respective of those initial links, not the ones I've changed it to with my colorscheme (non-links). 

~Can you run `:hi CurSearch` and let me know if it is indeed linked?~

I see you've noted:

>The strange thing is that in both cases if I looked at highlight groups using :highlight, CurSearch is shown as cleared.

I'll look at this ASAP. Thanks for the report.

**Comment by jghauser** [comment] 2022-09-05 07:06
I'm not sure if I have the same issue, but for me, the `Normal` highlight group isn't tinted and it's not linked... 

`:hi Normal`
```
Normal         xxx guifg=#d4d8d6 guisp=#d4d8d6
```
I'll open another issue if you think this is a different problem.

**Comment by levouh** [comment] 2022-09-05 17:13
Looking at this now - will let you know @jghauser.

**Comment by levouh** [comment] 2022-09-05 19:05
@andrewferrier taking a look at your [colorscheme](https://github.com/ellisonleao/gruvbox.nvim), it does not define `CurSearch`.

Has `CurSearch` been defined by the time that you load `tint`? The way `tint` works, it will only define colors in either of the two highlight namespaces it uses based on the colors set in the global highlight namespace at the time that the plugin is loaded (or your colorscheme changes).

**Comment by levouh** [comment] 2022-09-05 19:07
@jghauser same general question - when is `Normal` defined relative to when `tint` is loaded?

**Comment by levouh** [comment] 2022-09-05 23:27
Some notes on what is happening here (and a potential workaround) in #19 @andrewferrier. I'm still not 100% sure what is up in your case @jghauser - would need more information.

**Comment by jghauser** [comment] 2022-09-06 10:07
@levouh, I figured it out. At least when using lush, it's necessary that `NormalNC` has a `fg` defined. Once I did that, it started working as expected! :)

**Comment by levouh** [comment] 2022-09-06 13:00
> @levouh, I figured it out. At least when using lush, it's necessary that `NormalNC` has a `fg` defined. Once I did that, it started working as expected! :)

That makes sense, as `NormalNC` "replaces" `Normal` in unfocused windows. Glad you figured it out! I'll make a note about `NC` groups in general in the README.

**Comment by andrewferrier** [comment] 2022-09-08 17:25
Apologies for the delay in responding.

So for what it's worth, I was also seeing the same issue as @jghauser with `Normal`, I hadn't noticed that before. It looks like `gruvbox` does not set this by default. If I set it (and set up my `requires` correctly in my packer config to make sure `gruvbox` is loaded before `tint`), this problem goes away. I wonder if it would be worth `tint` taking control of `NormalNC` if it's not set and setting it to the same value as `Normal`, but with the tinting applied? `gruvbox` may not be the only colorscheme which is "badly behaved" in this respect (although to be fair it's not expecting a tint on inactive windows, so the more I think about this I definitely think it might be something `tint` should take control of?).

---

As far as the original `CurSearch` issue is concerned - no, CurSearch is not defined by `gruvbox` at all as far as I can see. It looks like NeoVim by default sets it to `CurSearch xxx cterm=reverse gui=reverse` - in other words, there are no colors defined, it just reverses the text. But if I check it with `tint` installed/loaded, it instead shows as `cleared`, and I don't see the reversed text.

**Comment by norseghost** [comment] 2022-09-09 02:07
> gruvbox may not be the only colorscheme which is "badly behaved" in this respect

a cursory look seems to indicate nord.nvim doesn't set `NormalNC` either.

>  I wonder if it would be worth tint taking control of NormalNC if it's not set and setting it to the same value as Normal, but with the tinting applied? 

this seems like a decent idea to me.

**Comment by levouh** [comment] 2022-09-09 03:32
I think I'd rather do something like:

```lua
require("tint").setup({
  link_if_not_defined = {
    NormalNC = "Normal",
  }
})
```

or similar for "generically handling highlight groups that are not defined when `tint` is loaded". Obviously this extends itself to "highlight groups not defined at all", however it is also not much overhead to just doing something like:

```lua
vim.api.nvim_set_hl(0, "NormalNC", { link = "Normal" })

require("tint").setup()
```

Curious on your thoughts on that @norseghost @andrewferrier. I think the benefit of doing it through `tint` itself would be that things like common highlight groups that people often have problems with would be fixed automatically (like `NormalNC`).

---

>As far as the original CurSearch issue is concerned - no, CurSearch is not defined by gruvbox at all as far as I can see. It looks like NeoVim by default sets it to CurSearch xxx cterm=reverse gui=reverse - in other words, there are no colors defined, it just reverses the text. But if I check it with tint installed/loaded, it instead shows as cleared, and I don't see the reversed text.

When I do `nvim --clean` and run `:verbose hi CurSearch` I get the same `CurSearch      xxx cleared` @andrewferrier. I'm curious if you have something else setting it that is just not working correctly? If you do something like `grep -r CurSearch ~/path/to/my/packer/dir` does anything show up? Obviously something like an `:h autocmd` that triggers whenever a highlight is defined would be ideal, but while that does not exist I am also looking at other (performance-respecting) options to see if there is a generically better way around this (as it is obviously a pain).

**Comment by andrewferrier** [comment] 2022-09-09 07:57
So on the `NormalNC` "issue" - I haven't investigated very deeply, but I think it's quite likely that a lot of NeoVim/Vim colorschemes won't set values such as `NormalNC` explicitly, because it looks like Vim just defaults to using the value of `Normal` if `NormalNC` is not set.

I'm not sure how your tinting is being done precisely, but it looks like what's happening is that `Normal` is being tinted, but `NormalNC` is being used as the original value of `Normal` when it's not set/linked.

I think auto-linking is definitely a good workaround in the short-to-medium-term (but I strongly feel you should have a default list of groups in that `link_if_not_defined` attribute, as many, maybe even most, people will hit this...) but I wonder if the root issue lies upstream? Now we are in this model where you can have different highlights in different windows, is there really a role for special "inactive" highlights like `NormalNC` at all? Maybe that's worth a NeoVim bug?

Also, should we split this out into a separate bug? It feels like it's not directly related to the CurSearch issue...

---

I'll look into the `CurSearch` issue and come back to you....

**Comment by andrewferrier** [comment] 2022-09-09 08:26
On the `CurSearch` issue... I'm really struggling to narrow this one down right now. I think I've confirmed the following things, though:

* You were right and I was wrong... `CurSearch` is set to `cleared` by default. I cannot recreate the `reverse=true` right now.

* I only see the problem *once* a split has been made (i.e. once tint's logic kicks in). If I do a search before splitting NeoVim, the current search highlighted looks normal (the same as the other search results). If I do it afterward, I get the behaviour where it looks like `Normal`.

* I've tried stripping out almost all my plugins - including my colorscheme, `gruvbox` - and the problem still occurs - so I don't think it's directly related to the colorscheme.

**Comment by andrewferrier** [comment] 2022-09-09 10:53
I wonder if this issue is related to the `NormalNC` problem: https://github.com/neovim/neovim/issues/20065.

**Comment by levouh** [comment] 2022-09-11 14:21
@andrewferrier I setup your whole config to debug myself a bit - when I first start things up (I've removed some of your noted workarounds in `gruvbox.lua` for `tint`), I can check `CurSearch` and get:

```
:hi CurSearch                                                                                                                                                                                                                                  
CurSearch      xxx cleared                                                                                                                                                                                                                     
```

This is after doing:

1. Open `nvim -u /tmp/nvim-test/init.lua` (which is your `init.lua` file)
2. `:e init.lua` (I get some errors with `BufEnter` autocommands about `fasd` not being available, however I cannot imagine this makes a difference)
3. I can execute a search as well as run `:hi CurSearch` and do not see that it is setup at all.

Does this seem right to you? Want to make sure that my "reproduce steps" are correct before doing anything else.

---

Also when setting things up, I had issues with things like `require("...")` (where `...` is something needs to be installed, e.g. `treesitter`) being in files in the `plugin/` directory at the top level. The problem being that files in this directory get automatically loaded by `nvim`, so e.g. your `packer_config.lua` never gets to run because these files fail first.

How do you usually install your setup from scratch? I have to put a `require("packer_config")` at the bottom of your `init.lua` and then run your custom `:PackerSync` before things would even boot up normally.

**Comment by levouh** [comment] 2022-09-11 14:33
Moved discussion of `NormalNC` stuff to #29 if anyone is interested or has stuff to add there. Will keep this thread focused on `CurSearch` stuff (which is somewhat related, but still separate enough to warrant a new issue at the moment).

**Comment by levouh** [comment] 2023-01-26 15:50
Closing this just to clean up. Feel free to open a  new issue if the issue persists.

**Closed as completed by levouh** 2023-01-26 15:50 UTC
